### ISSUE TITLE
GrapesJS plugin breaks new Mautic installations

### ISSUE THREAD

**Issue by dennisameling** [mautic/plugin-grapesjs-builder#59]
When trying to do a fresh installation based on Mautic's 3.3.0-rc release, the installer fails due to the `GrapesJsBuilderBundle`:

![image](https://user-images.githubusercontent.com/17739158/108241472-2b217c00-714c-11eb-9bea-d9fc76f18ace.png)

Steps to reproduce:
1. Clone the `features` branch from https://github.com/mautic/mautic (downloading the latest 3.3.0-rc release package also works, but won't give you detailed errors from dev mode).
2. Open `https://YOUR_MAUTIC_URL/index_dev.php`. You will be redirected to Mautic's installer.
3. See the error pop up.

**The problem is that the GrapesJsBundle is trying to contact Mautic's database **before** Mautic is configured completely, so database credentials aren't configured at that point yet.**

Full stack trace:

```
[2021-02-17 17:13:58] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 93 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)
[stacktrace]
#0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(166): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))
#1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(154): Doctrine\\DBAL\\DBALException::wrapException(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'An exception oc...')
#2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(28): Doctrine\\DBAL\\DBALException::driverException(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException))
#3 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(362): Doctrine\\DBAL\\Driver\\PDOMySql\\Driver->connect(Array, NULL, NULL, Array)
#4 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1443): Doctrine\\DBAL\\Connection->connect()
#5 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(890): Doctrine\\DBAL\\Connection->getWrappedConnection()
#6 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(718): Doctrine\\DBAL\\Connection->executeQuery('SELECT t0.id AS...', Array, Array)
#7 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php(193): Doctrine\\ORM\\Persisters\\Entity\\BasicEntityPersister->load(Array, NULL, NULL, Array, NULL, 1, NULL)
#8 /var/www/html/app/bundles/IntegrationsBundle/Helper/IntegrationsHelper.php(108): Doctrine\\ORM\\EntityRepository->findOneBy(Array)
#9 /var/www/html/app/bundles/IntegrationsBundle/Helper/IntegrationsHelper.php(74): Mautic\\IntegrationsBundle\\Helper\\IntegrationsHelper->getIntegrationConfiguration(Object(MauticPlugin\\GrapesJsBuilderBundle\\Integration\\GrapesJsBuilderIntegration))
#10 /var/www/html/plugins/GrapesJsBuilderBundle/Integration/Config.php(53): Mautic\\IntegrationsBundle\\Helper\\IntegrationsHelper->getIntegration('grapesjsbuilder')
#11 /var/www/html/plugins/GrapesJsBuilderBundle/Integration/Config.php(26): MauticPlugin\\GrapesJsBuilderBundle\\Integration\\Config->getIntegrationEntity()
#12 /var/www/html/plugins/GrapesJsBuilderBundle/EventSubscriber/AssetsSubscriber.php(33): MauticPlugin\\GrapesJsBuilderBundle\\Integration\\Config->isPublished()
#13 /var/www/html/vendor/symfony/event-dispatcher/Debug/WrappedListener.php(115): MauticPlugin\\GrapesJsBuilderBundle\\EventSubscriber\\AssetsSubscriber->injectAssets(Object(Mautic\\CoreBundle\\Event\\CustomAssetsEvent), 'mautic.view_inj...', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))
#14 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(214): Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener->__invoke(Object(Mautic\\CoreBundle\\Event\\CustomAssetsEvent), 'mautic.view_inj...', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))
#15 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'mautic.view_inj...', Object(Mautic\\CoreBundle\\Event\\CustomAssetsEvent))
#16 /var/www/html/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(143): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch('mautic.view_inj...', Object(Mautic\\CoreBundle\\Event\\CustomAssetsEvent))
#17 /var/www/html/app/bundles/CoreBundle/EventListener/AssetsSubscriber.php(55): Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher->dispatch('mautic.view_inj...', Object(Mautic\\CoreBundle\\Event\\CustomAssetsEvent))
#18 /var/www/html/vendor/symfony/event-dispatcher/Debug/WrappedListener.php(115): Mautic\\CoreBundle\\EventListener\\AssetsSubscriber->fetchCustomAssets(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent), 'kernel.request', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))
#19 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(214): Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener->__invoke(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent), 'kernel.request', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))
#20 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent))
#21 /var/www/html/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(143): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch('kernel.request', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent))
#22 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(127): Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher->dispatch('kernel.request', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent))
#23 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#24 /var/www/html/vendor/symfony/http-kernel/Kernel.php(200): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#25 /var/www/html/app/AppKernel.php(104): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#26 /var/www/html/app/middlewares/CORSMiddleware.php(91): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#27 /var/www/html/app/middlewares/CatchExceptionMiddleware.php(43): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#28 /var/www/html/app/middlewares/Dev/IpRestrictMiddleware.php(61): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#29 /var/www/html/app/middlewares/VersionCheckMiddleware.php(67): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#30 /var/www/html/app/middlewares/TrustMiddleware.php(51): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#31 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#32 /var/www/html/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#33 /var/www/html/index_dev.php(25): Stack\
un(Object(Stack\\StackedHttpKernel))
#34 {main}
"} 
```

**Comment by mohit-rocks** [comment]
Created a PR for the fix https://github.com/mautic/plugin-grapesjs-builder/pull/61
